title: LAGAX
description: "Comercializadora industrial en Monterrey, Saltillo y Torreón. Servicios de importación, exportación, logística Impo-Export, distribución de productos industriales, asesorías y soluciones comerciales en Coahuila y Nuevo León."
url: "https://www.lagax.shop"
baseurl: ""
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_backlinks: true
  entity_output: symbolic
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false